#!/bin/sh
# THIS FILE IS PART OF LibreBoot PROJECT NMTech0x90
# web_backup.sh - 采用定期备份、md5文件值校验、邮件接收日志及报警等。持续更新中.....
# THIS PROGRAM IS FREE SOFTWARE, web_backup.sh, IS LICENSED UNDER NMTech0x90.
# YOU SHOULD HAVE RECEIVED A COPY OF GNU General Public License v3.0, IF NOT Please delete immediately 
# Copyright (c) 2017 NMTech0x90
# Author Mail:NMTech@Aliyun.Com

# QMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNDDDbbNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNM
# QNQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ@QMM#hQD@@QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQN
# QNQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ@DQJMJ00h%%WhUQ@@@@QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQN
# QNQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ@QbJ0||&ppp|@WW%WWWWhU@@@QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQN
# QNQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ@b0M$00Jd00Jpppn2pJ#WWWWWWWhQ@QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQN
# QNQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQJ|p|VO&0|00$0|dd0JH#WWWWWWWWWWWh@QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQN
# QNQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQMpSpn&VO&JOV0OJ&00|Q%%WWWWWWWWWWWWh@QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQN
# QNQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQJmJVMdd&MppppppB||NW%WWWWWWWWWWWWWWhQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQN
# QNQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ&0OO00OBpOpSnnSXp|JNDUhhWWWWWWWWWWWWWhDQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQN
# QNQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQUDJ|&B||B&$JMNQQH##WWWW#W#UUN@QUDHhWW%%WWh@@QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQN
# QNQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ@0ppnp#WWW%%%%%%%%%%%%%%%%%%%%%%%%W#QJOJUWWWhQ@NXUQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQN
# QNQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQdd|&OBU%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%WHNM0UWWHb6UQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQN
# QNQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ@pG6pQW%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#JpDW#SQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQN
# QNQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ&mOB&|@W%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%0|@W&U@QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQN
# QNQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ$/XpXX8XQ%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%WB&p|BUQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQN
# QNQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQbABB$B||nW%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%Q|Jm@mQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQN
# QNQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQMX8p2u[XH%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%W|B|pUpQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQN
# QNQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQN8|X(unQ%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#&&BDWXQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQN
# QNQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ$CpBXp2H%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#B0BhH8QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQN
# QNQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQN|S6|Xp|h%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%MBM%WnQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQN
# QNQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ@08(///0W%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%WpH%W|QD@@@@QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQN
# QNQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ@Q@m6[uEAVW%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%h0WWWJWW#HUQQ@@@@@@QQQQQQQQQQQQQQQQQQQQQQQQQQQQN
# QNQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ@@DNDM@NHh#WUM0B$|W%%%%%%%%%%%%%%%%%%%%%%%%%%%%UMWWWWJ%WWWWWWW##HUQ@@@@@@QQQQQQQQQQQQQQQQQQQQQQN
# QNQQQQQQQQQQQQQQQQQQQQQQQQQQQQ@DNbMMJMDQUhh#WWW##WWH0m||UW%%%%%%%%%%%%%%%%%%%%%%%%%#NWWWWWdWWWWWWWWWWWW#WW##hQ@@@QQQQQQQQQQQQQQQQQQQN
# QNQQQQQQQQQQQQQQQQQQQQQQQQQNbb@QhUh##WWWWWW#WW##hh###Ubd0&Q%%%%%%%%%%%%%%%%%%QUUhU#WWWWWWWWWWWWWWWWWWWWWWWWWWWWhQ@@QQQQQQQQQQQQQQQQQN
# QNQQQQQQQQQQQQQQQQQQQQQQ@MOMH##WWWWW##WW#h###########WWHV|m|UWW%%%%%%%%%%%%%%#HWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWh@@QUSJQQQQQQQQQQQN
# QNQQQQQQQQQQQQQQQQQQQQQbN00JNWW#hhhhW#HDJJ#WWWWW#WWWWWWWWJOO|0|JUW%%%%%%W%WhQppWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWhQ@USJQQQQQQQQQQQN
# QNQQQQQQQQQQQQQQQQQQQQBJH|&mOUMJ0|$mJdm|pH#NMh###UQDQhH#H6CMJMd$Xph%%WUNWh0BXoU%WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#hUnJQQQQQQQQQQQN
# QNQQQQQQQQQQQQQQQQQQQJDWMJ0dOM0MMOM|00&JVhJJMMNHWNMbQHQh@XXUHUUUdmX|Mm|#MXpSlD%WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWpJQQQQQQQQQQQN
# QNQQQQQQQQQQQQQQQQQQp&W#Jp0|VM0JO$00&&|OVQmDDDbbUbNNDQMdQdubUQQQUU@UUO#W|BJ8GWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW%&JQQQQQQQQQQQN
# QNQQQQQQQQQQQQQQQQ@@mdUW#MMJJMVM000JO0$MppSMDNNNMNN@OXp6mM2QUQUQUUUhUJW#J$JBmWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW%MQQQQQQQQQQQQN
# QNQQQQQQQQQQQQQQQ@QUUJ$QWQ0VJMV0Vd&|$|0JbMOQQUUQUQUUU|68|Pp@NNNNNbQ#bOWHOOdpA#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW%M#h@QQQQQQQQQN
# QNQQQQQQQQQQQQQN0QUbUhb|$JJ0JJJ0000VJO0QUUUHUQUQUQQQUUmp$0@NNNNNNbU#JMW@$OO&BUWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW%MWWQ@QQQQQQQQN
# QNQQQQQQQQQQQQQmNh@J0QhbMMMMJbMVJ0VJMBJ@@Mb0bUUQUQUUUHmBmUUQUUQUQQU#0QW@BdJJmbWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW%M#Wh@QQQQQQQQN
# QNQQQQQQQQQQQQBJhUU0m|JU@dJJd&0V&&|0J$QVpEE8GpQUUUQQJBpSpQUQQQQQU@hUmhWJm&J2n&bWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW%M#WWh@QQQQQQQN
# QNQQQQQQQQQQQNBhUUhM0V|MQNMVMO0M0J00bO|pXp|Bpm|bMJ|mBpB|dUUUUUUUUUWhJWhV0VMp|JSh%WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW%M#WWWU@QQQQQQN
# QNQQQQQQQQQQQdMHUQUUd|m|&|O0OO|OO|O$JpApG8pG6X82AXC8XGBuVUQQQQQQ@QWb|WUm|$m(BdMWWWWWWWWWWWWWWWWWWWWWWWWWW%h6Q%WWWWWWWW%M#WWWWQ@QQQQQN
# QNQQQQQQQQQQ@OQbVQUhUMV$JMQ@MVJ0b|JNbBOBm|NMpB|p$Bm|BB0XJHUUUQbNb@W||WbXpBn)QWWWWWWWWWWWWWWWWWWWWWWWWWWWW%h|H%WWWWWWWW%M#WWWW#QQQQQQN
# QNQQQQQQQQQDBp|mm$NQUUN|||U%QB0d0&VJBAEAuBUQpCGn288Gn2m/|UQQQ@QDDUW|MWJp|mmAW%WWWWWWWWWWWWWWWWWWWWWWWWWWW%QBWWWWWWWWWW%M#WWWWWh@QQQQN
# QNQQQQQQQQMM@h@NJ$bO@UhbMOQ%%DJMbMb0mCw}/QUhDm|S$JJmBpBSpHHUUQHUU#hJHWb|Md0|WWWWWWWWWWWWWWWWWWWWWWWWWWWWW%QM%WWWWWWWWW%M#WWWWWWh@QQQN
# QNQQQQQQ@@UUUUQNM|@N|m0Jpmmh%%b|$&[GXE8/|UQQQmKmJQ@X/[pBAQQQQ@U@@Wh|hW||OdppWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWQ#WWWWWWWWWW%M#WWWWWWWU@QQN
# QNQQQQQ@NDDMdb0VJ$MQhUMb0QbJ#%%#bJp|&pOBUUQHQbND@NDb[[m&pDHUUQUQUWH&Wh&M0MBpWWWWWWWWWWWWWWWWWWWWWWWWWWWW#m$W%WWWWWWWWW%M#WWWWWWWWU@QN
# QNQQQQQ@QJJMbNQQQQb@Uh#hW%W#hW%%%WQJ0J$bUQQQQQQU@QQUMupBXQUQQQU@UWN0WU|O|bmmWWWWWWWWWWWWWWWWWWWWWWWWWWWWVXmUWWWWWWWWWW%M#WWWWWWWWWU@N
# QNQQQQ@@hHUHHUHUU##WWWWhHhW%%%%%%%%H$N0bUQHQUUQUQUUUUSmnDUUUUQUQhWMMWD|MQO8U%WWWWWWWWWWWWWWWWWWWWWWWWWWWW|mmmWWWWWWWWW%M#WWWWWWWWWWUN
# QNQQQQ@QUUQUUHHhhhh#WWWWWHWW%%%%%%%Q&M&JU@NNNNNNNNN@&mEpUQUQQUQQhW0QW0|JVShWWWWWWWWWWWWWWWWWWWWWWWWWW%#Q%WQN$DWWWWWWWW%MWWWWWWWWWWWWU
# QNQQQQDQUHUUUUUUUUWWW#WW%%%%%%%%%%%JObd0N@NNNNNNNNN@pB2@UQUQQUQQWW0UW$&0XW%WWWWWWWWWWWNQ%WJWWWWWWWWWWW$U%%%%HUWWWWWWWW%JhWWWWWWWWWWWh
# QNQQQDbQ@@HUUUhhUH#h##WWWW%%%%%%%%WNJ0b$NUQUQUUQUQUU$|JUUQUQQUQQW#O#W|OJ8Q%WWWWWWWWWWW|Q%WJWWWWWWWWW%UB#%%%WJWWWWWWWWW%M#WWWWWWWWWWWQ
# QNQQQDBJUQUhhhhUUUUUUUUUhh#WW%%%%%W%Q|JddQQQQQQQUQQQQQUQQQQQQQQQWh|WQO&0bWWWWWWWWWW%WdBMWWJWWWWWWWWWWBBW%%@0UWWWWWWWWW%MWWWWWWWW#WWWD
# QNQQQQ@BMhUUHUHUUUUhhhHUhhhHUW%%%%%%%Q|bJbhQUUDbNNNNN@UUUUUUUQbJWU0WhQh#W%WWWWWWWW%WVXnpWWJWWWWWWWW%N[p%%HBh%WWWWWWWWW%MhWWWWWWWWWW#N
# QNQQQQQQ0|QUUQUUUHUUUHhHhUh#UU#%%%%%%%D&O0QQQQ@DDDD@N@QQQQQQQQbNW@J%hBO&VNUWWWWW%Wb|ppmpUWJWWWWWWW%WSGM%%JnQWWWWWWWWWW%M#WWWWWWWWWWUN
# QNQQQQQQQdMQhUHUhhhHhHUUhUhhWW#%%%%%%%%Q0MUUHUUUUHUHUUUUUQUUUUQ##VUW@00J0d0dNWW#QJ&dM0MVMWMWWWWWWW%QB0UWWWU#WWWWWWWWWWWM#WWWWWWWWhQ@N
# QNQQQQQQQQQ&|UQQUQQUUUUUHUUH#WhUW%%%%%%%@p0NNbNDDDND@QDQNDQQ@@QWbph#pBpBppBpp||pnBpBBpBpB@J%WWWWW%UX8XpdhWWWWWWWWWWWWW%M#WWWWWW#Q@@QN
# QNQQQQQQQQQQ|OQ@hUhhhhhhHhUHU##UQW%%%%%WB}/[[[[KK8SXmMBMJ@QHUQOhVp#hQUQQQ@DNbMJJJ000&&$||S/hWWWWW#d0MD#WWWWWWWWWWWWWWWWM#WWWWWU@@QQQN
# QNQQQQQQQQQQJmUUHhUUQUQQUQHHUh##hHW%WUpX//u//////2pnSm|mNhHhhQ0hJVWHW%WWWWWWWWWWWWWWWWWWWWOWWhMmB#W%%%WWWWWWWWWWWWWWWWWM#WWWhQ@QQQQQN
# QNQQQQQQQQQQ@bNbNQUUUHUhhHhHHhh##WUJSX8&E(///////6nXG|0$N#hhhUWW0UWUWWWWWWWWWWWWWWWWWWWWWWJ%WWWW#WWWWWWWWWWWWWWWWWWWWWWMWWhQ@QQQQQQQN
# QNQQQQQQQQQQQQQNMVJ0J@QUUUUUUhhUUV8262ppppGpCSSGBB||Om|NhUUUUUWQS@#HWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW%MQU@@QQQQQQQQN
# @MNNNNNNNNNNNNNNDDDNNNM0JJJDQJB6GCA8XAXn6XEp286G|BBB|OQUhQQQ@QWJ8UDQWWWWWWWWWWWWWWWWWWWWWW$WWWWWWWWWWWWWWWWWW##WWWWWWWWn$NNNNNNNNNNNM
# Backup Dir
BACKUP_NAME="/Backup_Web"
# Data Dir
DATADIR="/var/www/html"

# File First Name 
Name="Web"

#Please do not modify!
Name=$Name"_`date +%Y_%m_%d_%H_%M`"
File="$Name.tar.gz"
BACKDIR_Root=$BACKUP_NAME
BACKDIR="$BACKDIR_Root/`date +%Y_%m`"
BACKDIR_Log="$BACKDIR_Root/log"

# Log File
Log="$BACKDIR_Log/md5_$Name"

# Backup
if [ ! -d "$BACKDIR" ];then
	mkdir -p $BACKDIR
	if [ ! -d "$BACKDIR_Log" ];then
		mkdir -p $BACKDIR_Log 
	fi
fi
chmod -R 600 $BACKDIR_Root
umask 077 $BACKDIR
tar zcfP $BACKDIR/$File $DATADIR

# MD5 File Verification Results
if [ -z `grep "$BACKDIR/$File" "$BACKDIR_Root/Files_List.txt"` ];then
	echo "$BACKDIR/$File" >>"$BACKDIR_Root/Files_List.txt"
fi
md5sum "$BACKDIR/$File" >$Log
i=0
for T in `cat $BACKDIR_Root/Files_List.txt`
do
	i=$(($i+1))
	List[$i]=${T}
done
i=0
echo "Here is MD5 File Verification Results:"
for Check in `ls $BACKDIR_Log`
do
	md5_check="$BACKDIR_Log/${Check}"
	i=$(($i+1))
	if [ "`md5sum ${List[$i]}`" == "`cat $md5_check`" ]; then
		echo "$md5_check | Check MD5 Value Success"
	else
	#	echo "Error MD5 Value!"
		echo "$md5_check | Error MD5 Value!"
	fi
done
echo -e "\nThis is New Backup log:$Log\n`cat $Log`"
